# Generated by Django 5.1.6 on 2025-03-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('INR', 'Indian Rupee (₹)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)')], default='inr', max_length=3),
        ),
    ]
