# Generated by Django 5.1.6 on 2025-03-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tourpackage_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='currency',
            field=models.CharField(choices=[('USD', ' ($)'), ('INR', ' (₹)'), ('EUR', ' (€)'), ('GBP', ' (£)')], default='₹', max_length=3),
        ),
    ]
