# Generated by Django 5.1.6 on 2025-03-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tourpackage_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackage',
            old_name='available_slots',
            new_name='available_spots',
        ),
    ]
